import {
  Code, Smartphone, Palette, Sparkles, Image, PenTool, Camera, Video,
  Megaphone, Search, TrendingUp, Lightbulb, Headset, Repeat, Lock, FileText,
  Server, Plug, ShoppingCart, Globe, Wrench, Layers, Compass, Package, Film,
  Mic, Type, Languages, Mail, Star, Target, GraduationCap, CalendarDays,
  Calculator, ScrollText, Stamp,
  LayoutDashboard, Rocket, Cloud, GitBranch, BrainCircuit, Blocks, Terminal, Bug,
  Gamepad2, Database, Wand2, Shield, Contact, Briefcase, FileCode, MonitorPlay,
  Music, Shapes, Presentation, UserSearch,
  type LucideIcon,
} from "lucide-react";

export const TEMPLATE_ICONS: Record<string, LucideIcon> = {
  code: Code,
  smartphone: Smartphone,
  palette: Palette,
  sparkles: Sparkles,
  image: Image,
  pen: PenTool,
  camera: Camera,
  video: Video,
  megaphone: Megaphone,
  search: Search,
  "trending-up": TrendingUp,
  lightbulb: Lightbulb,
  headset: Headset,
  repeat: Repeat,
  lock: Lock,
  // Premium template library
  server: Server,
  plug: Plug,
  cart: ShoppingCart,
  globe: Globe,
  wrench: Wrench,
  layers: Layers,
  compass: Compass,
  box: Package,
  film: Film,
  mic: Mic,
  type: Type,
  languages: Languages,
  mail: Mail,
  star: Star,
  target: Target,
  graduation: GraduationCap,
  calendar: CalendarDays,
  calculator: Calculator,
  scroll: ScrollText,
  stamp: Stamp,
  // Dream library (developer flagship)
  dashboard: LayoutDashboard,
  rocket: Rocket,
  cloud: Cloud,
  "git-branch": GitBranch,
  brain: BrainCircuit,
  blocks: Blocks,
  terminal: Terminal,
  bug: Bug,
  // Extraordinary library (cross-industry flagship)
  gamepad: Gamepad2,
  database: Database,
  wand: Wand2,
  shield: Shield,
  contact: Contact,
  briefcase: Briefcase,
  "file-code": FileCode,
  "monitor-play": MonitorPlay,
  music: Music,
  shapes: Shapes,
  presentation: Presentation,
  "user-search": UserSearch,
};

export function templateIcon(key: string): LucideIcon {
  return TEMPLATE_ICONS[key] ?? FileText;
}
